// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoSNvaRupgGbT29I55BvdGycz9As4lPl8',
    appId: '1:394466476018:web:42148ff7193c0de1be756b',
    messagingSenderId: '394466476018',
    projectId: 'intelligent-pharmacy',
    authDomain: 'intelligent-pharmacy.firebaseapp.com',
    storageBucket: 'intelligent-pharmacy.appspot.com',
    measurementId: 'G-N4TNNJNFM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI59mcesF41_iKrh-CLZjIYI-4QqtOIUs',
    appId: '1:394466476018:android:9e541135b91510c1be756b',
    messagingSenderId: '394466476018',
    projectId: 'intelligent-pharmacy',
    storageBucket: 'intelligent-pharmacy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpmeSN51yLTaovsIB-MCYVvCu7jrs0AEc',
    appId: '1:394466476018:ios:4cc8fde6dc380ec9be756b',
    messagingSenderId: '394466476018',
    projectId: 'intelligent-pharmacy',
    storageBucket: 'intelligent-pharmacy.appspot.com',
    iosBundleId: 'com.example.intelligentpharmacy.intelligentPharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpmeSN51yLTaovsIB-MCYVvCu7jrs0AEc',
    appId: '1:394466476018:ios:5ef9ae3e53deb625be756b',
    messagingSenderId: '394466476018',
    projectId: 'intelligent-pharmacy',
    storageBucket: 'intelligent-pharmacy.appspot.com',
    iosBundleId: 'com.example.intelligentpharmacy.intelligentPharmacy.RunnerTests',
  );
}
